name: Build Docker Image

on:
  workflow_call:
    inputs:
      repository:
        description: 'Docker repository'
        type: string
        required: true
      image_name:
        description: 'Docker image name'
        type: string
        required: true
      tag:
        description: 'Docker image tag'
        type: string
        required: true
      context:
        description: 'Build context path'
        type: string
        required: false
        default: './'


jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          version: v0.22.0

      - name: Build Docker Image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ${{ inputs.context }}
          push: false
          load: true # make the image available later for the `docker save` step
          tags: ${{ inputs.repository }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Save Docker Image as tar
        run: docker save -o ${{ inputs.image_name }}.tar ${{ inputs.repository }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ inputs.image_name }}
          path: ${{ inputs.image_name }}.tar
          if-no-files-found: error
