# Changes here will be overwritten by Copier
_commit: f3c06fe
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Copier template for creating Python libraries and executables
python_ci_versions:
- 3.12.7
- 3.13.1
python_version: 3.12.7
repo_name: copier-python-package-template
ssh_port_number: 55874
template_uses_python: true

