# Changes here will be overwritten by Copier
_commit: 2a2a0a2
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
python_version: 3.13.1
repo_name: copier-python-package-template
ssh_port_number: 55874

