# Changes here will be overwritten by Copier
_commit: v0.0.6-6-g2b24a38
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Copier template for creating Python libraries and executables
python_ci_versions:
- 3.12.7
python_version: 3.12.7
repo_name: copier-python-package-template
repo_org_name: LabAutomationAndScreening
ssh_port_number: 55874
template_uses_pulumi: false
template_uses_python: true

