[project]
name = "copier-python-package-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    # Managed by upstream template
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-randomly>=3.16.0",
    "pyright>=1.1.390",
    "copier>=9.4.1",
    "copier-templates-extensions>=0.3.0"

    # Specific to this template


]
