version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        VENV_PATH: /workspaces/copier-python-package-template/.venv
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/copier-python-package-template:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/copier-python-package-template/.venv
    command: sleep infinity
    ports:
      - "55874:2222"
    environment:
      - AWS_PROFILE=localstack


volumes:
  python_venv: {}
